name: MobSF Scan Workflow

on:
  push:
    branches:
      - master

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MobSF Scanner
      run: pip install mobsfscan

    - name: Run MobSF Scan on Damn-Vulnerable-Bank/app directory
      run: mobsfscan path https://github.com/subhajit0x/Damn-Vulnerable-Bank/tree/master/DamnVulnerableBank/app  
