name: MobSF Scan Workflow

on:
  push:
    branches:
      - master

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MobSF Scanner
      run: pip install mobsfscan

    - name: Run MobSF Scan
      run: mobsfscan  ../../Damn-Vulnerable-Bank/DamnVulnerableBank/app --json
    - name: Cat MobSF results
      run: cat results.json

    - name: Encode results to Base64
      id: encode_results
      run: echo "::set-output name=base64_content::$(base64 -w 0 results.json)"

    - name: Decode and set as PR body
      id: decode_results
      run: echo "::set-output name=content::$(echo '${{ steps.encode_results.outputs.base64_content }}' | base64 --decode)"

    - name: Create Pull Request with MobSF Scan Results
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Add MobSF scan results
        title: MobSF Scan Results
        body: ${{ steps.decode_results.outputs.content }}
        branch: mobsf-scan-results
        path: results.json
